apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: my-django-app
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres